### ISSUE TITLE
fails to send identity on 1st page call

### ISSUE THREAD

**Issue by jongbeau** [segment-integrations/analytics.js-integration-hubspot#6] opened 2016-04-18 02:21 UTC
https://help.segment.com/hc/en-us/community/posts/205385493-HubSpot-integration-fails-to-send-identity-on-1st-page-call

**Comment by hankim813** [comment] 2016-04-18 21:04
Hey @jongbeau hmm did you remove the default `.page()` call from your Segment snippet? 

Hubspot integration has an `.assumePageview()` flag which basically means that when the library loads, HS internally tracks a "pageview" which is why we added this flag so that we don't double count pageviews when the Segment snippet calls `.page()`.

https://github.com/segment-integrations/analytics.js-integration-hubspot/blob/master/lib/index.js#L15

So I'm assuming that you added your `.identify()` call prior to the initial `.page()` call inside the snippet. But when that first `.page()` call gets invoked, we're ignoring it for HS. 

Unless Hubspot has documented ways to send user data upon their library initialization (which is when they track the first page call natively), I'm not sure if we can do anything on our end. 

Let me know if this makes sense!

**Comment by jongbeau** [comment] 2016-04-18 21:56
I did not remove the default `.page()` call.

And to be clear, the first `.page()` call is indeed being sent to HS, but it's missing the identity information. So I still think this is a bug..

**Comment by hankim813** [comment] 2016-04-18 22:46
You're seeing the `.page()` call being sent because that is actually HS's library doing that upon loading not the `.page()` call inside Segment snippet. You can test this behavior by removing the `.page()` call in the Segment snippet. You'd still see the first page call I believe..

After more digging because HS's first page call is out of our control (auto invoked by its library) we can't add the `.identify()` data so I don't think this is something we can fix on our end :p 

You might want to reach out to HS to see if they can allow you to modify the first page call that their JS library makes (or maybe this is a feature they have?)

**Comment by jongbeau** [comment] 2016-04-18 23:10
I confirmed that the `.page()` call that I'm referring to is called when I invoke segment's `window.analytics.page()`.

Here's a simple way to repro the issue using the browser developer tools:

```
// from the JS console

window.analytics.identify('12345', { name: 'John Smith', email: 'john@smith.com'})
window.analytics.page()
```

Go to the developer tools network tab and observe the request to track.hubspot.com is missing the identity in the query string params.

call `window.analytics.page()` again from the JS console and observe that the request to hubspot now has the identity in the query string.

**Comment by hankim813** [comment] 2016-04-19 00:40
@jongbeau hmmm not able to reproduce this issue: 

![](https://cloudup.com/cuA3ht1WqPn+)

You can see that the `i` parameter is present.

**Comment by jongbeau** [comment] 2016-04-19 15:27
@hankim813 - that's very strange. Here's what it looks like in my environment:

![image](https://cloud.githubusercontent.com/assets/2096970/14644896/3c325a62-0619-11e6-8e46-b04820393cbb.png)

If I call page again, it works correctly:

![image](https://cloud.githubusercontent.com/assets/2096970/14644920/4e93a3f0-0619-11e6-8581-68f366736ccf.png)

**Comment by hankim813** [comment] 2016-04-19 16:15
@jongbeau that is indeed strange. Calling in some reinforcements here... @f2prateek @sperand-io @ndhoule any idea what could be the cause here? Can you guys test this out and see if you can reproduce?

Jason -- do you know if this is happening on other browsers like safari? We're just using their JS library under the hood so I'm not quite sure why it's not working for you :/

**Comment by pudgereyem** [comment] 2017-03-16 09:58
Hey @hankim813 and @jongbeau!
We're also having what I think is the same problem (+ another one) with Hubspot.

## 1) First page call not being tracked in HS
We did some testing using `analytics.ready()` and it seems like the callback is only fired if we call `page()` before calling `ready()`.

This becomes a problem, because when we fire `page()` for the first time, analytics libraries (such as Hubspot) that are not loaded – does not track that `page()` event.

We're trying a workaround right now where we do something like:

1. `.page()` (we're sending this to integrations, but does not get tracked by HS)
2. `ready()`
  2.1 `.page()` – (we're sending this only to HS – refer to code below)

```
analytics.page()
analytics.ready(function() {
  analytics.identify();
  analytics.page(null, 'Name of Page', {}, {
    integrations: {
      'All': false,
      'HubSpot': true
    }
  });
})
```

## 2)`identify` must be called for HS to track
It also seems like we have to call `identify` for every new browser session (page refresh) for HS to start tracking. That's not expected behaviour, right?

---

ping @filipstefansson

**Comment by hankim813** [comment] 2017-03-16 18:31
@pudgereyem Hey thanks for the detailed message but going through our contact https://segment.com/help would be best here since we have bunch of tools to give us some good starting context around your project as well as work with your custom implementation. 

With that said, I believe this bug (re: ready not firing) was fixed in a later version of ajs-integration base class and hubspot looks like it's using an old version. I can bump the package dependency for that now

**Comment by Peripheral1994** [comment] 2017-03-16 19:38
Deployed to production, please let us know if this issue is not resolved so we can reopen!

**Closed by Peripheral1994** 2017-03-16 19:38 UTC
